/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_firesteel_shuffle_ReduceSHMShuffleStore_LocalKryoByteBufferBasedDeserializer */

#ifndef _Included_com_hp_hpl_firesteel_shuffle_ReduceSHMShuffleStore_LocalKryoByteBufferBasedDeserializer
#define _Included_com_hp_hpl_firesteel_shuffle_ReduceSHMShuffleStore_LocalKryoByteBufferBasedDeserializer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
