/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_firesteel_shuffle_ShuffleStoreManager */

#ifndef _Included_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
#define _Included_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
 * Method:    ninitialize
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager_ninitialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager_shutdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
 * Method:    ncleanup
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager_ncleanup
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
 * Method:    nformatshm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager_nformatshm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_hp_hpl_firesteel_shuffle_ShuffleStoreManager
 * Method:    nregistershm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_firesteel_shuffle_ShuffleStoreManager_nregistershm
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
