/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hp_hpl_edgepartition_EdgeMessageComputeAggregate */

#ifndef _Included_com_hp_hpl_edgepartition_EdgeMessageComputeAggregate
#define _Included_com_hp_hpl_edgepartition_EdgeMessageComputeAggregate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hp_hpl_edgepartition_EdgeMessageComputeAggregate
 * Method:    aggregateComputeMessages
 * Signature: (IIIJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_hp_hpl_edgepartition_EdgeMessageComputeAggregate_aggregateComputeMessages
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
